version: '3.3'

services:

  jenkins-agents:
    image: usgsastro/jenkinsagent
    environment:
      - COMMAND_OPTIONS="-master http://${MASTER_IP}:8080 -labels 'docker' -executors 5"
      - DOCKER_HOST="tcp://${MASTER_IP}:2376"
      - DOCKER_TLS_VERIFY=1
    volumes:
      - /var/lib/dockervols/.docker:/root/.docker
      - /var/lib/dockervols/jenkins-agent:/workspace
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
