version: '3.3'

services:

  jenkins-agents:
    image: usgsastro/jenkinsagent
    environment:
      - COMMAND_OPTIONS=-master http://astro-ci.wr.usgs.gov -labels 'docker' -executors 5
      - DOCKER_HOST=tcp://130.118.161.92:2376
      - DOCKER_TLS_VERIFY=1
    volumes:
      - /var/lib/dockervols/.docker:/home/jenkins/.docker
      - /var/lib/dockervols/jenkins-agent:/workspace
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
